# Deep RL hands-on by Maxim Lapan
## Chapter 3 Deep Learning with PyTorch
* conda activate gym 
  - which will work with torch 1.1, tensorflow 2.0 with CUDA 10
* this book use torch

In [2]:
import torch as th
import numpy as np

In [3]:
a = th.FloatTensor(3,2)
a

tensor([[0.0000e+00, 4.5852e-41],
        [6.5191e-10, 5.2601e+22],
        [1.3680e+22, 6.6645e-10]])

In [5]:
a.zero_() # make all contents of a to zero

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [7]:
th.FloatTensor([[1,2,3], [3,2,1]]) # make custom tensor with contents

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [9]:
n = np.zeros(shape=(3,2))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
b = th.tensor(n)
b # copy np.array as torch tensor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [22]:
n = np.zeros(shape=(3,2), dtype=np.float16) # you can determine the data type for memory efficiency
c = th.tensor(n, dtype=th.int8) # you can change the data type when copy the data into torch tensor
c

tensor([[0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int8)

In [26]:
a = th.tensor([1,2,3])
s = a.sum()
print(s)
print(s.item()) # you get the content of scalar tensor by using .item()
print(th.tensor(1)) # scalar tensor don't have []

tensor(6)
6
tensor(1)


In [36]:
a = th.FloatTensor([2,3])
a

tensor([2., 3.])

In [37]:
ca = a.cuda()
ca

tensor([2., 3.], device='cuda:0')

In [38]:
a + 2

tensor([4., 5.])

In [39]:
ca + 1

tensor([3., 4.], device='cuda:0')

In [40]:
ca.device

device(type='cuda', index=0)

In [46]:
c1a = ca.to('cuda:1')
c1a

tensor([2., 3.], device='cuda:1')

In [44]:
ca

tensor([2., 3.], device='cuda:0')

In [47]:
c1a +3

tensor([5., 6.], device='cuda:1')

## gradient

In [48]:
v1 = th.tensor([1.0, 1.0], requires_grad = True)
v2 = th.tensor([2.0, 2.0])
v_sum = v1 + v2
v_res = (v_sum*2).sum()
v_res

tensor(12., grad_fn=<SumBackward0>)

In [51]:
v1.is_leaf, v2.is_leaf

(True, True)

In [52]:
v_sum.is_leaf, v_res.is_leaf

(False, False)

In [53]:
v1.requires_grad, v2.requires_grad

(True, False)

In [54]:
v_sum.requires_grad, v_res.requires_grad

(True, True)

In [55]:
v_res.backward()

In [59]:
v1.grad # dv_res/dv1 = 2

tensor([2., 2.])

In [58]:
v2.grad

## making neural layer

In [112]:
import torch.nn as nn

In [113]:
l  = nn.Linear(2,5)
v = th.FloatTensor([1,2])
l(v) 

tensor([-1.3842,  1.4714, -0.3135, -1.2000, -0.1853], grad_fn=<AddBackward0>)

In [114]:
print(l.weight)
np_weight= l.weight.detach().numpy()

Parameter containing:
tensor([[-0.5853, -0.4061],
        [ 0.0932,  0.3391],
        [-0.0510,  0.0320],
        [-0.3806, -0.4625],
        [-0.1209, -0.1012]], requires_grad=True)


In [115]:
np_weight

array([[-0.58525914, -0.40605706],
       [ 0.09319538,  0.33909577],
       [-0.05104429,  0.03196275],
       [-0.3805729 , -0.46251208],
       [-0.12090588, -0.10118318]], dtype=float32)

In [116]:
print(l.bias)
np_bias = l.bias.detach().numpy()
np_bias

Parameter containing:
tensor([ 0.0132,  0.7000, -0.3264,  0.1056,  0.1380], requires_grad=True)


array([ 0.01319081,  0.7000485 , -0.32640296,  0.10560948,  0.13801771],
      dtype=float32)

In [125]:
np.matmul(np_weight, v.numpy()) + np_bias

array([-1.3841825 ,  1.4714354 , -0.31352174, -1.1999876 , -0.18525451],
      dtype=float32)